const itemName = {
  availtime: "",
  yearofexperience: "補習年資",
  experience: "教育機構經驗",
  highestteachinglevel:'最高可補年級',
  educationallevel:'教育程度',
  notes: '是否有筆記提供',
  schoolcat: '中學類別',
  year:'現時就讀年級',
  language: '授課語言',
  strength: '強項',
  genderrequirement: '導師性別要求',
  expectation:'期望目標',
  name: '中或英文身份證全名',
  nationality: '國藉',
  phoneno: '聯絡電話',
  address: '固定住宅地址',
  emergencycontact: '緊急聯絡人姓名',
  emergencyphone: '緊急聯絡人電話',
  occupation: '現時職業',
  secondaryschool: '就讀中學',
  primaryschool: '就讀小學',
  publicexamgrade:'香港中學會考分數（六科總分）',
  university: '就讀大學',
  major: '大學主修科目',
  othercert: '其他專業應可課程',
  others: '特別要求/其他資料/學習困難',
  intro: '自我介紹',
  subgrade: '公開試成績'
};

export default itemName;
